# Generated by Django 5.1.15 on 2026-08-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('exercise', 'Exercise'), ('reading', 'Reading')], default='article', max_length=20)),
                ('content_url', models.URLField(blank=True, default='', max_length=500)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of lesson within the skill.')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'lessons',
                'ordering': ['skill', 'order'],
            },
        ),
    ]
