# Generated by Django 5.1.15 on 2026-08-30 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
        ('learning', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Aggregated competency score (0.0 to 100.0).')),
                ('confidence', models.FloatField(default=0.0, help_text='Overall confidence score (0.0 to 1.0).')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='competencies.competency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competency Progress',
                'verbose_name_plural': 'Competency Progresses',
                'db_table': 'competency_progress',
                'unique_together': {('user', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='learning.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Completion',
                'verbose_name_plural': 'Lesson Completions',
                'db_table': 'lesson_completions',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mastery', models.FloatField(default=0.0, help_text='Mastery percentage (0.0 to 100.0).')),
                ('xp', models.PositiveIntegerField(default=0, help_text='Total XP earned in this skill.')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence metric (0.0 to 1.0).')),
                ('last_assessed_at', models.DateTimeField(blank=True, help_text='Timestamp of last assessment evaluation.', null=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Progress',
                'verbose_name_plural': 'Skill Progresses',
                'db_table': 'skill_progress',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
