# Generated by Django 5.1.15 on 2026-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_competencyprogress_lessoncompletion_skillprogress'),
        ('skills', '0002_skill_is_managed_skill_learning_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='authority_level',
            field=models.CharField(blank=True, default='', help_text='How authoritative the source is, e.g. industry-standard.', max_length=64),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_managed',
            field=models.BooleanField(default=False, help_text='True when this record is owned by a curriculum package.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Publisher of the linked resource, e.g. MDN, IETF, OWASP.', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source_id',
            field=models.SlugField(blank=True, default='', help_text='Curriculum resource ID this lesson points at. Empty for hand-authored lessons.', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='source_verified_at',
            field=models.DateField(blank=True, help_text='Date the curriculum last verified this resource URL.', null=True),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('is_managed', True)), fields=('skill', 'source_id'), name='unique_managed_lesson_per_skill_resource'),
        ),
    ]
