# Generated by Django 5.1.15 on 2026-08-31 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_lesson_authority_level_lesson_is_managed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attribution_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='commercial_use_allowed',
            field=models.BooleanField(default=False, help_text='False for non-commercial licences such as CC BY-NC-SA.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='license',
            field=models.CharField(blank=True, default='', help_text="SPDX-style identifier of the source's licence, e.g. CC-BY-SA-4.0.", max_length=128),
        ),
        migrations.AddField(
            model_name='lesson',
            name='license_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='license_verified',
            field=models.BooleanField(default=False, help_text='True only once a human has confirmed the licence against the source.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='link_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='link_status',
            field=models.CharField(blank=True, default='', help_text='Result of the last reachability check: ok, moved, or broken.', max_length=32),
        ),
        migrations.AddField(
            model_name='lesson',
            name='redistributable',
            field=models.BooleanField(default=False, help_text='Whether the licence permits copying this material into Progressio.'),
        ),
        migrations.CreateModel(
            name='StudyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchor', models.CharField(blank=True, default='', help_text='Fragment identifying the section to read, e.g. #idempotent_methods.', max_length=255)),
                ('prompt', models.TextField(help_text='What the learner should do with that section.')),
                ('checkpoint_question', models.TextField(blank=True, default='', help_text='Short question to confirm the section was understood.')),
                ('checkpoint_answer', models.CharField(blank=True, default='', help_text='Expected answer. Graded server-side and never serialized.', max_length=255)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_steps', to='learning.lesson')),
            ],
            options={
                'verbose_name': 'Study Step',
                'verbose_name_plural': 'Study Steps',
                'db_table': 'study_steps',
                'ordering': ['lesson', 'order'],
                'unique_together': {('lesson', 'order')},
            },
        ),
    ]
