# Generated by Django 5.1.15 on 2026-08-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_learning_minutes', models.PositiveIntegerField(default=0, help_text='Estimated time to learn this skill in minutes.')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='competencies.competency')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'db_table': 'skills',
                'ordering': ['competency', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='skills.skill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Skill Prerequisite',
                'verbose_name_plural': 'Skill Prerequisites',
                'db_table': 'skill_prerequisites',
                'unique_together': {('skill', 'required_skill')},
            },
        ),
    ]
