# Generated by Django 5.1.15 on 2026-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_managed',
            field=models.BooleanField(default=False, help_text='True when this record is owned by a curriculum package.'),
        ),
        migrations.AddField(
            model_name='skill',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list, help_text='What a learner can do once this skill is held.'),
        ),
    ]
