# Generated by Django 5.1.15 on 2026-08-30 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_hash', models.CharField(help_text='SHA-256 cryptographic hash of the canonical credential snapshot.', max_length=64)),
                ('transaction_hash', models.CharField(help_text='Immutable transaction hash on the blockchain.', max_length=66)),
                ('network', models.CharField(default='polygon-amoy', help_text='Blockchain network where proof is registered.', max_length=50)),
                ('block_number', models.PositiveIntegerField(blank=True, help_text='Block height of the registered transaction.', null=True)),
                ('verified', models.BooleanField(default=True, help_text='True if on-chain proof is confirmed valid.')),
                ('revoked', models.BooleanField(default=False, help_text='True if credential has been marked revoked on-chain.')),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_proof', to='credentials.credential')),
            ],
            options={
                'verbose_name': 'Blockchain Credential',
                'verbose_name_plural': 'Blockchain Credentials',
                'db_table': 'blockchain_credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
