# Generated by Django 5.1.15 on 2026-10-07 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('credentials', '0002_credential_issuance_key_alter_credential_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('credential_hash', models.CharField(max_length=64)),
                ('network', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=20)),
                ('endpoint_hash', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('sending', 'In flight'), ('unknown', 'Outcome unknown'), ('confirmed', 'Confirmed'), ('failed', 'Blocked or rejected')], default='ready', max_length=20)),
                ('active_attempt', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_delivery', to='credentials.credential')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProofAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=20)),
                ('outcome', models.CharField(default='started', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='blockchain.proofdelivery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
