# Generated by Django 5.1.15 on 2026-08-31 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=0, help_text='Estimated hours to reach this competency.'),
        ),
        migrations.AddField(
            model_name='competency',
            name='is_managed',
            field=models.BooleanField(default=False, help_text='True when this record is owned by a curriculum package.'),
        ),
        migrations.AddField(
            model_name='competency',
            name='learning_outcomes',
            field=models.JSONField(blank=True, default=list, help_text='What a learner can do once this competency is reached.'),
        ),
        migrations.AddField(
            model_name='competency',
            name='observable_behaviors',
            field=models.JSONField(blank=True, default=list, help_text='Externally observable evidence that this competency is held.'),
        ),
        migrations.CreateModel(
            name='CompetencyPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='competencies.competency')),
                ('required_competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='competencies.competency')),
            ],
            options={
                'verbose_name': 'Competency Prerequisite',
                'verbose_name_plural': 'Competency Prerequisites',
                'db_table': 'competency_prerequisites',
                'unique_together': {('competency', 'required_competency')},
            },
        ),
    ]
