# Generated by Django 5.1.15 on 2026-08-30 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('competencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique credential identifier.', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='draft', max_length=20)),
                ('score', models.FloatField(help_text='Final competency achievement score (0.0 to 100.0).')),
                ('issued_at', models.DateTimeField(blank=True, help_text='Timestamp when the credential was officially issued.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Snapshot metadata (student name, competency, track, metrics).')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='competencies.competency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'db_table': 'credentials',
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_url', models.URLField(blank=True, default='', max_length=500)),
                ('file_url', models.URLField(blank=True, default='', max_length=500)),
                ('demo_url', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='credentials.credential')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='assessments.submission')),
            ],
            options={
                'verbose_name': 'Credential Evidence',
                'verbose_name_plural': 'Credential Evidences',
                'db_table': 'credential_evidences',
                'ordering': ['-created_at'],
            },
        ),
    ]
