# Generated by Django 5.1.15 on 2026-10-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='issuance_key',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Awaiting proof confirmation'), ('failed', 'Proof blocked or rejected'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='draft', max_length=20),
        ),
    ]
