# Generated by Django 5.1.15 on 2026-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertrack',
            name='curriculum_schema_version',
            field=models.PositiveIntegerField(default=0, help_text='Schema version of the curriculum package.'),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='curriculum_version',
            field=models.CharField(blank=True, default='', help_text='Version of the curriculum package that defines this track.', max_length=32),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=0, help_text='Total estimated hours declared by the curriculum manifest.'),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='is_managed',
            field=models.BooleanField(default=False, help_text='True when this record is owned by a curriculum package and must not be edited by hand.'),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Curriculum manifest metadata (status, source, tags).'),
        ),
        migrations.AddField(
            model_name='careertrack',
            name='target_learner',
            field=models.TextField(blank=True, default='', help_text='Who this track is designed for, from the curriculum manifest.'),
        ),
    ]
