# Generated by Django 5.1.15 on 2026-08-30 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('challenge', 'Challenge'), ('project', 'Project')], default='quiz', max_length=20)),
                ('instructions', models.TextField(blank=True, default='')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Minimum score required to pass.')),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Maximum possible score.')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessments',
                'ordering': ['skill', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('evaluating', 'Evaluating'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Submission payload, answers, code, or repository metadata.')),
                ('score', models.FloatField(blank=True, help_text='Awarded score from 0 to max_score.', null=True)),
                ('feedback', models.TextField(blank=True, default='', help_text='Automated or evaluator feedback.')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when submission was finalized.', null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
