# Generated by Django 5.1.15 on 2026-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_diagnostic_and_grading'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='estimated_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Expected time to complete. Null while the curriculum leaves it undefined.', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='expected_evidence',
            field=models.JSONField(blank=True, default=list, help_text='Artifacts a learner must produce, from the curriculum.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_managed',
            field=models.BooleanField(default=False, help_text='True when this record is owned by a curriculum package.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='mastery_criteria',
            field=models.TextField(blank=True, default='', help_text='Curriculum-defined bar for counting this skill as mastered.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='objective',
            field=models.TextField(blank=True, default='', help_text='What this assessment is meant to establish.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='source_id',
            field=models.SlugField(blank=True, default='', help_text='Curriculum assessment ID. Empty for hand-authored assessments.', max_length=255),
        ),
    ]
