# Generated by Django 5.1.15 on 2026-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_estimated_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.JSONField(blank=True, default=list, help_text="Public question list for rule-graded assessments: [{'id', 'prompt', 'options': [{'value', 'label'}]}]. Never contains answers."),
        ),
    ]
