# Generated by Django 5.1.15 on 2026-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_assessment_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticquestion',
            name='source_id',
            field=models.SlugField(blank=True, default='', help_text='Curriculum diagnostic question ID. Empty for hand-authored questions.', max_length=255),
        ),
    ]
